import { stringify } from 'yaml';
import { McpClient, type ServerSpec } from './client.js';
import type { JsonSchema, ToolDefinition } from './types.js';

/** Connect to a server, discover its tools, and generate a ready-to-run
 * mcpt test file. Generated tests default to snapshot mode: the first
 * `mcpt run` records each tool's output, and every run after that is a
 * regression test. */
export async function generateTestFile(spec: ServerSpec): Promise<string> {
  const client = new McpClient(spec);
  let tools: ToolDefinition[];
  try {
    await client.start();
    tools = await client.listTools();
  } finally {
    await client.close();
  }

  const doc = {
    server: {
      command: spec.command,
      ...(spec.args?.length ? { args: spec.args } : {}),
    },
    ...(tools.length ? { expectTools: tools.map((t) => t.name) } : {}),
    tests: tools.map((tool) => ({
      name: `${tool.name}: ${firstSentence(tool.description) ?? 'returns a stable result'}`,
      tool: tool.name,
      args: sampleArguments(tool.inputSchema),
      expect: { snapshot: true },
    })),
  };

  const banner = [
    `# Generated by \`mcpt init\` against ${client.serverInfo.name ?? spec.command}`,
    `# 1. Review the sample arguments below — replace them with realistic values.`,
    `# 2. Run \`mcpt run\` once to record snapshots, then every run is a regression test.`,
    `# 3. Prefer explicit expectations (text/contains/json) for your most important tools.`,
    '',
  ].join('\n');

  return banner + stringify(doc);
}

/** Build plausible sample arguments from a tool's JSON Schema input. */
export function sampleArguments(schema: JsonSchema | undefined): Record<string, unknown> {
  if (!schema || schema.type !== 'object' || !schema.properties) return {};
  const required = new Set(schema.required ?? []);
  const args: Record<string, unknown> = {};
  for (const [name, prop] of Object.entries(schema.properties)) {
    // include required properties plus any with an obvious sample value
    if (required.has(name) || prop.default !== undefined || prop.examples?.length) {
      args[name] = sampleValue(prop, name);
    }
  }
  return args;
}

function sampleValue(schema: JsonSchema, hint: string): unknown {
  if (schema.default !== undefined) return schema.default;
  if (schema.examples?.length) return schema.examples[0];
  if (schema.enum?.length) return schema.enum[0];

  const type = Array.isArray(schema.type) ? schema.type[0] : schema.type;
  switch (type) {
    case 'string':
      return `TODO: ${schema.description ?? hint}`;
    case 'number':
    case 'integer':
      return 1;
    case 'boolean':
      return true;
    case 'array':
      return schema.items ? [sampleValue(schema.items, hint)] : [];
    case 'object':
      return sampleArguments(schema);
    default:
      return null;
  }
}

function firstSentence(text: string | undefined): string | undefined {
  if (!text) return undefined;
  const sentence = text.split(/[.\n]/)[0].trim();
  return sentence.length > 0 && sentence.length <= 80 ? sentence : sentence.slice(0, 77) + '…';
}
